chore: header token

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -51,16 +51,16 @@ runs:
         CCI_TOKEN: ${{ inputs.cci_token }}
         CCI_BUILD_NAME: ${{ inputs.docker_build_job_name }}
       run: 
-        PROJECT_SLUG=circleci/5JBARKjC9duevdMYTL5Eit/DxsBAJbPyXpz8qNfxBcuAV
-        echo "response:${CCI_RESPONSE}\n"
-        echo "Waiting 30 seconds before start checking CircleCI status.\n"
-        echo "Check on https://app.circleci.com/pipelines/$PROJECT_SLUG\n"
+        PIPELINE=https://app.circleci.com/pipelines/circleci/5JBARKjC9duevdMYTL5Eit/DxsBAJbPyXpz8qNfxBcuAV
+        echo "response:${CCI_RESPONSE}\\n"
+        echo "Waiting 30 seconds before start checking CircleCI status.\\n"
+        echo "Check on $PIPELINE - ${PIPELINE}\\n"
         sleep 60
-        
-        curl_status="(curl -sS \"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN\" | jq -Mre \".items[] | select(.name == \\\"${CCI_BUILD_NAME}\\\") | .status\"  || echo 'circleci_curl_fail')" 
+        curl -v --header "Circle-Token:${CCI_TOKEN}" \"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow\"
+        curl_status="(curl -sS --header "Circle-Token:${CCI_TOKEN}" \"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow\" | jq -Mre \".items[] | select(.name == \\\"${CCI_BUILD_NAME}\\\") | .status\"  || echo 'circleci_curl_fail')" 
         STATUS=$(eval $curl_status)
         
-        echo $STATUS
+        echo "status:$STATUS"
         echo 'Build failed'
         exit 1
 
