chore: format

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -52,4 +52,28 @@ runs:
         CCI_RESPONSE: ${{steps.trigger_cci.outputs.cci_response}}
         CCI_TOKEN: CCIPAT_RRpPzMAuryJfNHQAxNvBmz_e9e1ea64d666edf275d17b7bdd1bd76a5c280008
         CCI_BUILD_NAME: ${{ inputs.docker_build_job_name }}
-      run: "echo \"Waiting 30 seconds before start checking CircleCI status.\"\necho \"Check on https://app.circleci.com/pipelines/${PROJECT_SLUG}\"\nsleep 60\ncurl_status=\"(curl -sS \\\"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN\\\" | jq -Mre \\\".items[] | select(.name == \\\\\\\"${CCI_BUILD_NAME}\\\\\\\") | .status\\\"  || echo 'circleci_curl_fail')\" \nSTATUS='running'\nwhile [[ $STATUS = 'running' ]]; do\n  echo \"Pipeline status is $STATUS\"\n  sleep 10\n  STATUS=$(eval $curl_status)\n  if [[ $STATUS = 'circleci_curl_fail' ]]; then\n    sleep 5\n    STATUS=$(eval $curl_status)\n  fi\ndone\n\nif [[ $STATUS = 'success' ]]; then\n  echo 'Build completed successfully!'\n  exit 0\nfi\necho $STATUS\necho 'Build failed'\nexit 1\n"
+      run: 
+        echo "Waiting 30 seconds before start checking CircleCI status."
+        echo "Check on https://app.circleci.com/pipelines/{$PROJECT_SLUG}"
+        sleep 60
+        export CIRCLE_V2_TOKEN=CCIPAT_RRpPzMAuryJfNHQAxNvBmz_e9e1ea64d666edf275d17b7bdd1bd76a5c280008
+        curl_status="(curl -sS \"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN\" | jq -Mre \".items[] | select(.name == \\\"${CCI_BUILD_NAME}\\\") | .status\"  || echo 'circleci_curl_fail')" 
+        STATUS='running'
+        while [[ $STATUS = 'running' ]]; do
+          echo "Pipeline status is $STATUS"
+          sleep 10
+          STATUS=$(eval $curl_status)
+          if [[ $STATUS = 'circleci_curl_fail' ]]; then
+            sleep 5
+            STATUS=$(eval $curl_status)
+          fi
+        done
+
+        if [[ $STATUS = 'success' ]]; then
+          echo 'Build completed successfully!'
+          exit 0
+        fi
+        echo $STATUS
+        echo 'Build failed'
+        exit 1
+
