chore: use header token and github app urls (#4)
project slug hardcoded to labfolder(web) atm

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -29,20 +29,25 @@ runs:
     - name: Trigger CircleCI Build Workflow.
       shell: bash
       id: trigger_cci
+      env:
+        CCI_TOKEN: ${{ inputs.cci_token }}
       run: |
-        PROJECT_SLUG="circleci/5JBARKjC9duevdMYTL5Eit/DxsBAJbPyXpz8qNfxBcuAV"
+        PROJECT_SLUG=circleci/5JBARKjC9duevdMYTL5Eit/DxsBAJbPyXpz8qNfxBcuAV
+        REQUEST_PARAMS='{\"definition_id\": \"3736b82a-cefd-46a2-b50d-96291ec9099b\", \"config\": {\"branch\": \"$GITHUB_REF_NAME\"}, \"checkout\": {\"branch\": \"$GITHUB_REF_NAME\"}, \"parameters\": {\"${{ inputs.build_param }}\": true}}'
+        
         echo "Triggering pipeline using the {${{ inputs.build_param }}} parameter in the {${{ inputs.branch }}} branch for the {$PROJECT_SLUG} project SLUG."
-
-        RESPONSE=$(curl -sS -u "${{ inputs.cci_token }}": --header "Content-Type: application/json" \
-          -d "{\"branch\":\"${{ inputs.branch }}\",\"parameters\": {\"${{ inputs.build_param }}\": true}}" \
-          https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline | jq -r '.id')
-
-        echo "::set-output name=cci_response::${RESPONSE}"
+        
+        eval echo "$REQUEST_PARAMS" > pipelineparams.json
+        RESPONSE=$(curl --header "Content-Type: application/json" \
+          --header "Circle-Token: ${CCI_TOKEN}" \
+          -d @pipelineparams.json \
+          https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline/run | jq -r '.id')
+        echo "CCI_RESPONSE=${RESPONSE}" >> "$GITHUB_OUTPUT"
     - name: Wait for CircleCI Build Workflow.
       if: ${{ inputs.wait_for_cci_result }}
       shell: bash
       env:
-        CCI_RESPONSE: ${{steps.trigger_cci.outputs.cci_response}}
+        CCI_RESPONSE: ${{steps.trigger_cci.outputs.CCI_RESPONSE}}
         CCI_TOKEN: ${{ inputs.cci_token }}
         CCI_BUILD_NAME: ${{ inputs.docker_build_job_name }}
-      run: "echo \"Waiting 30 seconds before start checking CircleCI status.\"\necho \"Check on https://app.circleci.com/pipelines/${PROJECT_SLUG}\"\nsleep 60\ncurl_status=\"(curl -sS \\\"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN\\\" | jq -Mre \\\".items[] | select(.name == \\\\\\\"${CCI_BUILD_NAME}\\\\\\\") | .status\\\"  || echo 'circleci_curl_fail')\" \nSTATUS='running'\nwhile [[ $STATUS = 'running' ]]; do\n  echo \"Pipeline status is $STATUS\"\n  sleep 10\n  STATUS=$(eval $curl_status)\n  if [[ $STATUS = 'circleci_curl_fail' ]]; then\n    sleep 5\n    STATUS=$(eval $curl_status)\n  fi\ndone\n\nif [[ $STATUS = 'success' ]]; then\n  echo 'Build completed successfully!'\n  exit 0\nfi\necho $STATUS\necho 'Build failed'\nexit 1\n"
+      run: "echo \"Waiting 30 seconds before start checking CircleCI status.\"\necho \"Check on https://app.circleci.com/pipelines/${PROJECT_SLUG}\"\nsleep 60\ncurl_status=\"(curl -sS --header \\\"Content-Type: application/json\\\" --header \\\"Circle-Token: ${CCI_TOKEN}\\\" \\\"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow\\\" | jq -Mre \\\".items[] | select(.name == \\\\\\\"${CCI_BUILD_NAME}\\\\\\\") | .status\\\"  || echo 'circleci_curl_fail')\" \nSTATUS='running'\nwhile [[ $STATUS = 'running' ]]; do\n  echo \"Pipeline status is $STATUS\"\n  sleep 10\n  STATUS=$(eval $curl_status)\n  if [[ $STATUS = 'circleci_curl_fail' ]]; then\n    sleep 5\n    STATUS=$(eval $curl_status)\n  fi\ndone\n\nif [[ $STATUS = 'success' ]]; then\n  echo 'Build completed successfully!'\n  exit 0\nfi\necho $STATUS\necho 'Build failed'\nexit 1\n"
