Chore/fix circleci curl fail
Laboperator-server building error solved.

diff --git a/circleci/trigger/action.yml b/circleci/trigger/action.yml
--- a/circleci/trigger/action.yml
+++ b/circleci/trigger/action.yml
@@ -54,12 +54,17 @@ runs:
       run: |
         echo "Waiting 30 seconds before start checking CircleCI status."
         echo "Check on https://app.circleci.com/pipelines/github/labforward/${{ github.event.repository.name }}"
-        sleep 30
-        STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Mre ".items[] | select(.name == \"${CCI_BUILD_NAME}\") | .status"  || echo '"circleci_curl_fail"')
+        sleep 15
+        curl_status="(curl -sS \"https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN\" | jq -Mre \".items[] | select(.name == \\\"${CCI_BUILD_NAME}\\\") | .status\"  || echo 'circleci_curl_fail')" 
+        STATUS='running'
         while [[ $STATUS = 'running' ]]; do
           echo "Pipeline status is $STATUS"
           sleep 10
-          STATUS=$(curl -sS "https://circleci.com/api/v2/pipeline/$CCI_RESPONSE/workflow?circle-token=$CCI_TOKEN" | jq -Mre ".items[] | select(.name == \"${CCI_BUILD_NAME}\") | .status" || echo '"circleci_curl_fail"')
+          STATUS=$(eval $curl_status)
+          if [[ $STATUS = 'circleci_curl_fail' ]]; then
+            sleep 5
+            STATUS=$(eval $curl_status)
+          fi
         done
         
         if [[ $STATUS = 'success' ]]; then
